/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package datalibrary;

import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class FormBuku extends javax.swing.JFrame {
    

    private Boolean isUpdate = false;
    dbConnection dbcon = new dbConnection();
    private int idRow;
    /**
     * Creates new form FormBuku
     */
    public FormBuku() {
        initComponents();
        dbcon.connect();
        btn_del.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBukuFB = new javax.swing.JLabel();
        tf_desc = new javax.swing.JTextField();
        lblCoverFB = new javax.swing.JLabel();
        lblPenerbitFB = new javax.swing.JLabel();
        lblAuthorFB = new javax.swing.JLabel();
        lblDescFB = new javax.swing.JLabel();
        tf_penerbit = new javax.swing.JTextField();
        tf_author = new javax.swing.JTextField();
        tf_cover = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tf_judul = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        btn_del = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBukuFB.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        lblBukuFB.setText("Buku");

        tf_desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_descActionPerformed(evt);
            }
        });

        lblCoverFB.setText("Cover");

        lblPenerbitFB.setText("Penerbit");

        lblAuthorFB.setText("Author");

        lblDescFB.setText("Deskripsi");

        tf_penerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_penerbitActionPerformed(evt);
            }
        });

        tf_cover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_coverActionPerformed(evt);
            }
        });

        jLabel1.setText("Judul");

        tf_judul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_judulActionPerformed(evt);
            }
        });

        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_del.setText("Delete");
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(lblBukuFB))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPenerbitFB)
                            .addComponent(lblAuthorFB)
                            .addComponent(lblDescFB)
                            .addComponent(lblCoverFB)
                            .addComponent(jLabel1))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_del)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_add)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_cancel))
                            .addComponent(tf_penerbit)
                            .addComponent(tf_author)
                            .addComponent(tf_desc)
                            .addComponent(tf_cover, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_judul))))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblBukuFB)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_judul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPenerbitFB)
                    .addComponent(tf_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAuthorFB)
                    .addComponent(tf_author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescFB)
                    .addComponent(tf_desc))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_cover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCoverFB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add)
                    .addComponent(btn_cancel)
                    .addComponent(btn_del))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_penerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_penerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_penerbitActionPerformed

    private void tf_judulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_judulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_judulActionPerformed

    private void tf_descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_descActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_descActionPerformed

    private void tf_coverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_coverActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tf_coverActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        
        if (tf_judul.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Judul tidak boleh kosong.");
        }
        else if (tf_penerbit.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Penerbit tidak boleh kosong.");
        }
        else if (tf_author.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Author tidak boleh kosong.");
        }
        else {
            // Get Data
            String judul = tf_judul.getText();
            String penerbit = tf_penerbit.getText();
            String author = tf_author.getText();
            String desc = tf_desc.getText();
            
            // Jika semua text field terisi, add/update data
            if (isUpdate == false) {
                //insertData
                String ins = "insert into tb_buku (judul, penerbit, author, desc) values (\"" + 
                        judul + "\", \"" + penerbit + "\", \"" + author + "\", \"" + desc + "\")";
                System.out.println(ins);
                dbcon.Query(ins);
                
                // Bersihkan textfield setelah insert/add data
                clearTextField();
            }
            else {
                //updateData
                String upd = "update tb_buku set judul=\"" + judul + "\", penerbit=\"" + penerbit + "\", author=\"" +
                        author + "\", desc=\"" + desc + "\" where id_buku=\"" + idRow + "\"";
                System.out.println(upd);
                dbcon.Query(upd);
                
                // Bersihkan textfield setelah update
                clearTextField();
                btn_add.setText("Add");
                this.isUpdate = false;
            }
        }
        
        this.setVisible(false);
        Menu m = new Menu();
        m.updateBuku();
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        clearTextField();
        btn_add.setText("Add");
        this.setVisible(false);
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
        // TODO add your handling code here:
        //Delete Data
        String del = "delete from tb_buku where id_buku=\"" + idRow + "\"";
        System.out.println(del);
        dbcon.Query(del);

        // Bersihkan textfield setelah update
        clearTextField();
        btn_add.setText("Add");
        this.isUpdate = false;
    }//GEN-LAST:event_btn_delActionPerformed

    private void clearTextField() {
        tf_author.setText("");
        tf_judul.setText("");
        tf_penerbit.setText("");
        tf_desc.setText("");
        tf_cover.setText("");
    }
    
    public void setTF(int cek, int id, String s1, String s2, String s3, String s4, String s5) {
        
        if(cek >= 0) {
            tf_judul.setText(s1);
            tf_penerbit.setText(s2);
            tf_author.setText(s3);
            tf_desc.setText(s4);
            tf_cover.setText(s5);
            
            btn_add.setText("Update");
            btn_del.setVisible(true);
            this.isUpdate = true;
            idRow = id;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_del;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAuthorFB;
    private javax.swing.JLabel lblBukuFB;
    private javax.swing.JLabel lblCoverFB;
    private javax.swing.JLabel lblDescFB;
    private javax.swing.JLabel lblPenerbitFB;
    private javax.swing.JTextField tf_author;
    private javax.swing.JTextField tf_cover;
    private javax.swing.JTextField tf_desc;
    private javax.swing.JTextField tf_judul;
    private javax.swing.JTextField tf_penerbit;
    // End of variables declaration//GEN-END:variables
}
